### ISSUE TITLE
select带有远程搜索时的无法正常显示

### ISSUE THREAD

**Issue by taipeiwu** [cipchk/ng-alain#2275]
### Reproduction link
[https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
參考 select 选择器(https://ng-alain.com/form/select/zh?#form-select-search) > 搜索用户 或 在线校验器(https://ng-alain.com/form-pages/validator/zh) > 顺序 > 水平/垂直

### What is expected?
宽度要依远程内容自适化或依ui.width条件显示

### What is actually happening?
栏位宽度无法正常显示，看不到选项内容

| Environment | Info |
|---|---|
| ng-alain | 13.5.2 |
| Browser | Chrome 102 |

**Comment by cipchk** [comment]
设置一下 `placeholder` 或者全局方式增加 less:

```less
.sf__item .ant-select {
  min-width: 200px; // 修改一个自己觉得的合理值。
}
```
