### ISSUE TITLE
modelhelper在360浏览器下显示异常

### ISSUE THREAD

**Issue by snowchenlei** [cipchk/ng-alain#2310]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-jw7l7v?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-jw7l7v?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1. 打开[ng-alain文档](https://ng-alain.com/theme/modal/zh)页面
2. 滚动到代码演示
3. 点击Open/Static按钮即可看到效果

### What is expected?
模态框显示在中间

### What is actually happening?
模态框显示在左上角并出现了滚动条

| Environment | Info |
|---|---|
| ng-alain | 14.1.0 |
| Browser | 360安全浏览器13 |

**Comment by snowchenlei** [comment]
This problem should be caused by 360 Secure Browser not supporting inset attributes

**Comment by cipchk** [comment]
尝试在 https://ng.ant.design/components/modal/en 是否也一样，若是的话，只能你自己写样式覆盖，因为我所了解好像 360浏览器 并不是[支持环境](https://ng.ant.design/docs/introduce/zh#%E6%94%AF%E6%8C%81%E7%8E%AF%E5%A2%83)之类。

**Comment by snowchenlei** [comment]
> 尝试在 https://ng.ant.design/components/modal/en 是否也一样，若是的话，只能你自己写样式覆盖，因为我所了解好像 360浏览器 并不是[支持环境](https://ng.ant.design/docs/introduce/zh#%E6%94%AF%E6%8C%81%E7%8E%AF%E5%A2%83)之类。

ng-zorro是可以的，因为他没有使用inset这个css属性，还是用的之前的left,top这些
``` css
/*ng-zorro*/
.ant-modal-wrap {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    overflow: auto;
    outline: 0;
    -webkit-overflow-scrolling: touch;
}
/*ng-alain*/
.ant-modal-wrap {
    position: fixed;
    inset: 0;
    overflow: auto;
    outline: 0;
    -webkit-overflow-scrolling: touch;
}
```

**Comment by cipchk** [comment]
尝试了创建一个新的 angular 项目，也会自动转化成 `inset`：

```less
/* style.less */
/* You can add global styles to this file, and also import other style files */
body {
  position: relative;
  top: 0;
  right: 0;
  left: 0;
  bottom: 0;
}
```

`ng b` 以后也会变成：

```css
body{position:relative;inset:0}
```

看起来像是postcss某个插件更新版本引起，但我尝试找不到是哪里；为何 NG-ZORRO 没有，估计发布至今已经过好几个星期了。
